
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Sun Nov 25 17:43:41 CST 2018
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int STRLIT = 50;
  static final int rw_WHILE = 28;
  static final int rw_BOOL = 16;
  static final int LBRACKET = 19;
  static final int INCREMENT = 37;
  static final int rw_IF = 14;
  static final int SLASH = 22;
  static final int rw_CONTINUE = 34;
  static final int rw_FALSE = 21;
  static final int LPAREN = 5;
  static final int SEMI = 4;
  static final int rw_PRINT = 36;
  static final int rw_TRUE = 32;
  static final int DECREMENT = 38;
  static final int MINUS = 11;
  static final int RPAREN = 6;
  static final int NOT = 46;
  static final int AND = 39;
  static final int rw_VOID = 43;
  static final int INTLIT = 3;
  static final int LT = 27;
  static final int rw_CONST = 26;
  static final int OR = 40;
  static final int COMMA = 45;
  static final int rw_ELSE = 23;
  static final int GEQ = 20;
  static final int PLUS = 10;
  static final int rw_READ = 42;
  static final int rw_INT = 15;
  static final int EOF = 0;
  static final int rw_FOR = 29;
  static final int RBRACKET = 33;
  static final int error = 1;
  static final int COR = 18;
  static final int rw_CLASS = 17;
  static final int rw_RETURN = 41;
  static final int EQ = 12;
  static final int ASG = 7;
  static final int TIMES = 44;
  static final int CHARLIT = 49;
  static final int COLON = 35;
  static final int LBRACE = 8;
  static final int rw_CHAR = 30;
  static final int RBRACE = 9;
  static final int CAND = 25;
  static final int LEQ = 31;
  static final int rw_BREAK = 47;
  static final int INT_BITSTR = 48;
  static final int GT = 24;
  static final int NOTEQ = 13;
  static final int IDENTIFIER = 2;
}

